version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: startup_arena
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CONNECTION_STRING: postgres://postgres:postgres@db:5432/startup_arena
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:
